### ISSUE TITLE
ERROR: Warning message.

### ISSUE THREAD

**Issue by TheGreatOneYouKnow** [btcpayserver/opencart#14]
In Checkout, after I click on **Pay with Bitcoin** button, I get this message:
`Warning: Undefined array key "total" in /home/***/***/***/extension/btcpay/catalog/controller/payment/btcpay.php on line 411Warning: Undefined array key "currency_code" in /home/***/***/***/extension/btcpay/catalog/controller/payment/btcpay.php on line 411Opencart\System\Library\Cart\Currency::getValue(): Argument #1 ($currency) must be of type string, null given, called in /home/***/***/***/extension/btcpay/catalog/controller/payment/btcpay.php on line 442: in /home/***/***/***/system/library/cart/currency.php on line 177`

That is when the Modal/iFrame mode is unchecked. When it is checked, the invoice just doesn't show.

Anyone knows what could be the problem, please?

Thanks.

**Comment by ndeet** [comment]
I tried several things to reproduce this locally but was not able to. From discussions in chat it seems that there is some problem with the users sessions. As if the backend does not receive the order details anymore and then fails because all the required data fields are empty (even though the cart still working and showing them).

Likely this only happens with testing and using multiple back and forth steps on the checkout.

@TheGreatOneYouKnow do you have any way to reproduce the problem reliably. I saw that same error on your site but could not reproduce on any of my installations. Can you give me more details about your PHP version and operating system installed? PHP version and other useful information is shown at the top of the BTCPay settings form in OpenCart
![image](https://github.com/btcpayserver/opencart/assets/1136761/7cd9e221-86d5-4b98-830f-009c0e4b6591)

Thanks in advance!

**Comment by TheGreatOneYouKnow** [comment]
Hello, this is how to reproduce that warning message:

1. Make an order via the BTCPay server. (without paying, just the return button once the terminal shows up).
2. Go to shopping cart and empty it.
3. Then go to Orders in OpenCart admin and delete that order.

After that, next order will reproduce that warning message.

**Comment by TheGreatOneYouKnow** [comment]
This is what I have there: Debug info: OpenCart 4.0.2.3 with BTCPay Extension 4.2.1 on PHP 8.1.24

**Comment by ndeet** [comment]
Hi @TheGreatOneYouKnow had finally time to debug this fully.

The problem is that the session stores the old order id which you just deleted and causing the error. I would assume this happens only when testing as I can't imagine that some body deletes orders that quickly in the admin backend otherwise. So to solve that problem just do not delete orders until a few days have passed so that the session of the user is renewed. 

This has nothing to do with the plugin but session handling of OC. I opened an issue on OC for it https://github.com/opencart/opencart/issues/12800

I will add a check and error message to our plugin for that case but as said this rarely will happen on production and can be completely avoided if orders are not deleted quickly after they were created but a few days later.
